#!/usr/bin/perl


$url = "www.example.com";
$command=`/usr/bin/curl $url`;
$title = "COMP 490 CGI-BIN";
 
print "Content-type: text/html\n\n";
print "COMP 490 CGI-BIN Program by Karan Bhamra\n\n\n\n\n\n";

print $command;
